# This file is generated by rake. Do not edit.

module JNI
  JNI::EnvFunctions.each_function do |name, arg_types, return_type, block|
  	callback name, arg_types, return_type
  end
  
  class EnvStruct < FFI::Struct
    layout :ExceptionOccurred, :ExceptionOccurred, 120,
           :NewGlobalRef, :NewGlobalRef, 168,
           :DeleteGlobalRef, :DeleteGlobalRef, 176,
           :IsSameObject, :IsSameObject, 192,
           :GetObjectClass, :GetObjectClass, 248,
           :GetMethodID, :GetMethodID, 264,
           :CallByteMethod, :CallByteMethod, 320,
           :CallCharMethod, :CallCharMethod, 344,
           :CallShortMethod, :CallShortMethod, 368,
           :CallIntMethod, :CallIntMethod, 392,
           :CallLongMethod, :CallLongMethod, 416,
           :CallFloatMethod, :CallFloatMethod, 440,
           :CallDoubleMethod, :CallDoubleMethod, 464,
           :CallByteMethodV, :CallByteMethodV, 328,
           :CallCharMethodV, :CallCharMethodV, 352,
           :CallShortMethodV, :CallShortMethodV, 376,
           :CallIntMethodV, :CallIntMethodV, 400,
           :CallLongMethodV, :CallLongMethodV, 424,
           :CallFloatMethodV, :CallFloatMethodV, 448,
           :CallDoubleMethodV, :CallDoubleMethodV, 472,
           :GetFieldID, :GetFieldID, 752,
           :GetObjectField, :GetObjectField, 760,
           :GetBooleanField, :GetBooleanField, 768,
           :GetByteField, :GetByteField, 776,
           :GetCharField, :GetCharField, 784,
           :GetShortField, :GetShortField, 792,
           :GetIntField, :GetIntField, 800,
           :GetLongField, :GetLongField, 808,
           :GetFloatField, :GetFloatField, 816,
           :GetDoubleField, :GetDoubleField, 824,
           :SetBooleanField, :SetBooleanField, 840,
           :SetByteField, :SetByteField, 848,
           :SetCharField, :SetCharField, 856,
           :SetShortField, :SetShortField, 864,
           :SetIntField, :SetIntField, 872,
           :SetLongField, :SetLongField, 880,
           :SetFloatField, :SetFloatField, 888,
           :SetDoubleField, :SetDoubleField, 896,
           :GetStaticMethodID, :GetStaticMethodID, 904,
           :CallStaticByteMethod, :CallStaticByteMethod, 960,
           :CallStaticCharMethod, :CallStaticCharMethod, 984,
           :CallStaticShortMethod, :CallStaticShortMethod, 1008,
           :CallStaticIntMethod, :CallStaticIntMethod, 1032,
           :CallStaticLongMethod, :CallStaticLongMethod, 1056,
           :CallStaticFloatMethod, :CallStaticFloatMethod, 1080,
           :CallStaticDoubleMethod, :CallStaticDoubleMethod, 1104,
           :CallStaticByteMethodV, :CallStaticByteMethodV, 968,
           :CallStaticCharMethodV, :CallStaticCharMethodV, 992,
           :CallStaticShortMethodV, :CallStaticShortMethodV, 1016,
           :CallStaticIntMethodV, :CallStaticIntMethodV, 1040,
           :CallStaticLongMethodV, :CallStaticLongMethodV, 1064,
           :CallStaticFloatMethodV, :CallStaticFloatMethodV, 1088,
           :CallStaticDoubleMethodV, :CallStaticDoubleMethodV, 1112,
           :GetStringUTFChars, :GetStringUTFChars, 1352,
           :ReleaseStringUTFChars, :ReleaseStringUTFChars, 1360,
           :NewByteArray, :NewByteArray, 1408,
           :NewCharArray, :NewCharArray, 1416,
           :NewShortArray, :NewShortArray, 1424,
           :NewIntArray, :NewIntArray, 1432,
           :NewLongArray, :NewLongArray, 1440,
           :NewFloatArray, :NewFloatArray, 1448,
           :NewDoubleArray, :NewDoubleArray, 1456,
           :GetBooleanArrayElements, :GetBooleanArrayElements, 1464,
           :GetByteArrayElements, :GetByteArrayElements, 1472,
           :GetCharArrayElements, :GetCharArrayElements, 1480,
           :GetShortArrayElements, :GetShortArrayElements, 1488,
           :GetIntArrayElements, :GetIntArrayElements, 1496,
           :GetLongArrayElements, :GetLongArrayElements, 1504,
           :GetFloatArrayElements, :GetFloatArrayElements, 1512,
           :GetDoubleArrayElements, :GetDoubleArrayElements, 1520,
           :ReleaseBooleanArrayElements, :ReleaseBooleanArrayElements, 1528,
           :ReleaseByteArrayElements, :ReleaseByteArrayElements, 1536,
           :ReleaseCharArrayElements, :ReleaseCharArrayElements, 1544,
           :ReleaseShortArrayElements, :ReleaseShortArrayElements, 1552,
           :ReleaseIntArrayElements, :ReleaseIntArrayElements, 1560,
           :ReleaseLongArrayElements, :ReleaseLongArrayElements, 1568,
           :ReleaseFloatArrayElements, :ReleaseFloatArrayElements, 1576,
           :ReleaseDoubleArrayElements, :ReleaseDoubleArrayElements, 1584,
           :GetByteArrayRegion, :GetByteArrayRegion, 1600,
           :GetCharArrayRegion, :GetCharArrayRegion, 1608,
           :GetShortArrayRegion, :GetShortArrayRegion, 1616,
           :GetIntArrayRegion, :GetIntArrayRegion, 1624,
           :GetLongArrayRegion, :GetLongArrayRegion, 1632,
           :GetFloatArrayRegion, :GetFloatArrayRegion, 1640,
           :GetDoubleArrayRegion, :GetDoubleArrayRegion, 1648,
           :SetByteArrayRegion, :SetByteArrayRegion, 1664,
           :SetCharArrayRegion, :SetCharArrayRegion, 1672,
           :SetShortArrayRegion, :SetShortArrayRegion, 1680,
           :SetIntArrayRegion, :SetIntArrayRegion, 1688,
           :SetLongArrayRegion, :SetLongArrayRegion, 1696,
           :SetFloatArrayRegion, :SetFloatArrayRegion, 1704,
           :SetDoubleArrayRegion, :SetDoubleArrayRegion, 1712,
           :GetJavaVM, :GetJavaVM, 1752
  end
  
  JNI::JvmFunctions.each_function do |name, arg_types, return_type, block|
  	callback name, arg_types, return_type
  end
  
  class JvmStruct < FFI::Struct
    layout :AttachCurrentThread, :AttachCurrentThread, 32








  end
end
